modLoader = "javafml"
loaderVersion = "[43,)"
#issueTrackerURL = ""
license = "All Rights Reserved"

[[mods]]
modId = "aegis"
version = "${version}"
displayName = "Aegis"
authors = "RedPxnda/Panderva"
description = '''
A simple mod that revamps Minecraft's armor system.
'''
#logoFile = ""

[[dependencies.aegis]]
modId = "forge"
mandatory = true
versionRange = "[43,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aegis]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.aegis]]
modId = "architectury"
mandatory = true
versionRange = "[6.2.43,)"
ordering = "AFTER"
side = "BOTH"